### ISSUE TITLE
Multiple authors and affiliations in beamerposter header

### ISSUE THREAD

**Issue by llcc** [deselaers/latex-beamerposter#1]
I am trying to add multiple authors and affiliations in the header of `beamerposter` by referring to [How can I make a LaTeX poster with all affiliations on the same line, using Beamer?](http://tex.stackexchange.com/questions/187385/how-can-i-make-a-latex-poster-with-all-affiliations-on-the-same-line-using-beam). 

```
\title{This is a beamerposter header with multiple authors and affiliations} 
\author[shortname]{Author1 \inst{1} \and Author2 \inst{2} \and Author3  \inst{3}}
\institute[shortinst]{\inst{1} Affil1 \and \inst{2} Afil2 \and \inst{3} Afil3 }
```

But for my situation, the authors can be sucessfully added, but none of the affiliations can be shown, like:

```
This is a beamerposter header with multiple authors and affiliations 
                Author1   Author2   Author3
```

Because I couldn't add `maketitle` command to document or it will generate a 
separate title page. Therefore, without `maketitle` command, is there a solution about this?

Here is a small document for reproducing the problem. Thanks!

```
\documentclass[final]{beamer}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage[orientation=portrait,size=a2,scale=1.4,debug]{beamerposter}
\usetheme{RJH}
\usepackage[]{subfig}
\usepackage[absolute,overlay]{textpos}
\setlength{\TPHorizModule}{1cm}
\setlength{\TPVertModule}{1cm}
\footer{a footer}
\title{This is a beamerposter header with multiple authors and affiliations} 
\author[shortname]{Author1 \inst{1} \and Author2 \inst{2} \and Author3  \inst{3}}
\institute[shortinst]{\inst{1} Affil1 \and \inst{2} Afil2 \and \inst{3} Afil3 }
\begin{document}


\begin{frame}[t]{}
\begin{columns}
\begin{column}[t]{0.49\textwidth}
\begin{block}{Introduction}
Introduction section
\end{block}
\end{column}

\begin{column}[t]{0.49\textwidth}
\begin{block}{Results}
Results section
\end{block}
\end{column}
\end{columns}
\end{frame}

\end{document}
```

**Comment by deselaers** [comment]
This is not really an issue with beamer poster but a question that you could resolve on the mailinglist.
