### ISSUE TITLE
Default paper formats slightly off

### ISSUE THREAD

**Issue by PJ-Prins** [deselaers/latex-beamerposter#10]
Some paper sizes defined in beamerposter.sty differ from the official A series formats. The sizes should be as follows: (current values in comments)

    %a0
    \edef\paperwidthValue{118.9} % {118.82}
    \edef\paperheightValue{84.1} % {83.96}
    \edef\textwidthValue{117.9}  % =\paperwidthValue - 1  % {117.82}
    \edef\textheightValue{83.1}  % =\paperheightValue - 1 % {82.96}
    \edef\fontscale{1.0}
    \or
    %a1
    \edef\paperwidthValue{84.1}  % {83.96}
    \edef\paperheightValue{59.4}
    \edef\textwidthValue{83.1}   % =\paperwidthValue - 1  % {82.96}
    \edef\textheightValue{58.4}
    \edef\fontscale{0.70710678}  % fontscale=(1/sqrt(2))^1
    \or
    %a2
    \edef\paperwidthValue{59.4}
    \edef\paperheightValue{42.0} % {41.98}
    \edef\textwidthValue{58.4}
    \edef\textheightValue{41.0}  % =\paperheightValue - 1 % {40.98}
    \edef\fontscale{0.5}         % fontscale=(1/sqrt(2))^2
    \or
    %a3
    \edef\paperwidthValue{42.0}  % {41.98}
    \edef\paperheightValue{29.7}
    \edef\textwidthValue{41.0}   % =\paperwidthValue - 1  % {40.98}
    \edef\textheightValue{28.7}
    \edef\fontscale{0.35355339}  % fontscale=(1/sqrt(2))^3

(a4 sizes are correct)

**Comment by deselaers** [comment]
Feel free to send me a pull request.

t.

Am Do., 12. Apr. 2018 um 23:02 Uhr schrieb PJ-Prins <
notifications@github.com>:
