### ISSUE TITLE
Add theme example?

### ISSUE THREAD

**Issue by TheChymera** [deselaers/latex-beamerposter#2]
First off, many thanks for writing this package! I had initially been advised to use tikzposter, but seeing as tikz does not work with `pgf` (and thus with the way I have grown accustomed to using pythontex), I had to find something different.

It turns out that this package not only supports `pgf`, but has also been easier for me to hack in other ways.

In any case, I have finished creating a [poster](http://chymera.eu/posters/znz_poster/poster.pdf) with latex-beamerposter, the soirce code of which you can find [on bitbucket](https://bitbucket.org/TheChymera/znz_poster/src). It depends on external stuff such as pythontex and my own analysis scripts, so it may not in and of itself be suitable as a ready-to-go example. However, as part of this, I have created a new [color theme](https://bitbucket.org/TheChymera/znz_poster/src/e2df0567186c3b95c673137d578554fee2f05e2a/beamerthemeZH.sty?fileviewer=file-view-default) based on my university's corporate identity. I would be very happy if you would be interested to include it!

**Comment by deselaers** [comment]
Hi Christian,

Sounds great. Do you want to send us a pull request?

Cheers,
thomas

2016-04-28 3:45 GMT-07:00 Horea Christian notifications@github.com:

**Comment by TheChymera** [comment]
Sounds great! I'll strip my example poster of pythontex and submit the full example.

**Comment by deselaers** [comment]
Thanks, merged your pull request.
