### ISSUE TITLE
Multiple affiliation support?

### ISSUE THREAD

**Issue by TheChymera** [deselaers/latex-beamerposter#6]
Does beamerposter support multiple affiliations? Is there any way to add superscript notes to map the authors to different institutions (and/or one author to multiple institutions) ?

**Comment by deselaers** [comment]
Hi,

I am pretty sure I have hacked this at some point in the past using $^1$
and $^2$ both in the list of authors and in the affiliations but I don't
think there's dedicated support for it.

t.

2016-10-23 20:55 GMT+02:00 Horea Christian notifications@github.com:

**Comment by TheChymera** [comment]
I have added an example of that hack in #7

**Comment by deselaers** [comment]
Thanks. Looks great.
t.

2016-10-25 23:51 GMT+02:00 Horea Christian notifications@github.com:
