### ISSUE TITLE
Include themes in the CTAN package

### ISSUE THREAD

**Issue by xuhdev** [deselaers/latex-beamerposter#8]
The themes in the theme directory are not in the CTAN package. This always leads to manual download of these themes.

**Comment by deselaers** [comment]
Hi,

This sounds like a good idea.
If you want to send me a pull request I'll merge it and try to push a new
release into CTAN.

Cheers,
t

2017-06-02 7:27 GMT+02:00 Hong <notifications@github.com>:

**Comment by deselaers** [comment]
I have just uploaded a new version to CTAN. It will probably take a few days to propagate.
